language: ruby
rvm:
- "1.9.3"
- "2.2.9"
- "2.3.6"

env:
  global:
    - DPL_VERSION=$(ruby -I lib -r dpl/version.rb -e "puts DPL::VERSION.succ + \".travis.#{ENV['TRAVIS_JOB_NUMBER']}\"")

matrix:
  allow_failures:
    - rvm: "1.9.3"

sudo: false

cache:
  directories:
    - vendor/cache

before_install:
  - gem update bundler

script:
  - bundle exec rspec spec/cli_spec.rb spec/provider_spec.rb
  - gem build dpl.gemspec && gem install dpl-*.gem
  - echo -e "\n${ANSI_GREEN}Run specs${ANSI_RESET}"
  - |
    spec_errors=0
    for f in dpl-*.gemspec; do
      base=${f%*.gemspec}; name=${base#dpl-*}
      echo -e "\n${ANSI_GREEN}${base}${ANSI_RESET}\n"
      echo -e "source 'https://rubygems.org'\ngemspec :name => \"dpl-${name}\", :glob => \"dpl-${name}.gemspec\"" > Gemfile-${name}
      bundle install --gemfile Gemfile-${name} --path=vendor/cache/dpl-${name} --binstubs=bin && ./bin/rspec spec/provider/${name}_spec.rb || let spec_errors=$spec_errors+1
    done
    test $spec_errors -eq 0
  - echo -e "\n${ANSI_GREEN}Install gem and invoke dpl${ANSI_RESET}"
  - |
    no_err=0
    for f in dpl-*.gemspec; do
      base=${f%*.gemspec}; name=${base#dpl-*}
      echo -e "\n${ANSI_GREEN}${base}${ANSI_RESET}\n"
      gem build --silent $f && gem install dpl-${name}-*.gem && ( dpl --provider=${name} --no-deploy ) || let no_err=$no_err+1
    done
    test $no_err -eq 0
  # - bundle exec rake && gem build dpl.gemspec && gem install dpl-*.gem && dpl --provider=script --script='echo foo'

deploy:
  provider: rubygems
  api_key:
    secure: ZmZoDL1tilWvQrqRWDm2K4xQ5Grt9eRJzYVZPLANR0P1TM5BJBLk+UhWCWCPkkDVIBWMa5ANsiFYBxtH65Lw+uqMztSpVusk0l0LQXZGv9jMpT9445A8008U3vvfS0ke7IG8Q4bMAC7Sd6VGaiHDyZC7zmNvnqMpmVX7ShcgBME=
  gem: dpl
  on:
    repo: travis-ci/dpl
    rvm: 2.2.6

notifications:
  webhooks: "http://requestb.in/1guaq7t1"
