language: ruby

rvm:
- 1.9.3
- 2.0.0
- 2.1.5
- "2.2.5"
- "2.3.1"

matrix:
  allow_failures:
    - rvm: "2.2.5"
    - rvm: "2.3.1"

sudo: false

cache: bundler

script:
  - bundle exec rake && gem build dpl.gemspec && gem install dpl-*.gem && dpl --provider=script --script='echo foo'
