language: ruby

rvm: 2.3.1

sudo: false

cache: bundler

script: bundle exec rake

deploy:
  provider: releases
  user: waghanza
  password: "${GITHUB_PASSWORD}"
  repo: dpl
  skip_cleanup: true
  edge:
    source: waghanza/dpl
    branch: conditional_require
