language: ruby
rvm:
- "1.9.3"
- "2.2.9"
- "2.3.6"

env:
  global:
    - PREREQUISITE_PROVIDERS="cloud_foundry"

matrix:
  allow_failures:
    - rvm: "1.9.3"

sudo: false

cache: bundler

before_install:
  - gem update bundler

script:
  - gem build dpl.gemspec && gem install dpl-*.gem
  - |
    for p in $PREREQUISITE_PROVIDERS; do
      gem build dpl-${p}.gemspec && gem install dpl-${p}-*.gem
    done
  - |
    for f in dpl-*.gemspec; do
      base=${f%*.gemspec}; name=${base#dpl-*}
      gem build $f && gem install dpl-${name}-*.gem && ( yes | dpl --provider=${name} --skip-cleanup=true ) || true
    done
  # - bundle exec rake && gem build dpl.gemspec && gem install dpl-*.gem && dpl --provider=script --script='echo foo'

deploy:
  provider: rubygems
  api_key:
    secure: ZmZoDL1tilWvQrqRWDm2K4xQ5Grt9eRJzYVZPLANR0P1TM5BJBLk+UhWCWCPkkDVIBWMa5ANsiFYBxtH65Lw+uqMztSpVusk0l0LQXZGv9jMpT9445A8008U3vvfS0ke7IG8Q4bMAC7Sd6VGaiHDyZC7zmNvnqMpmVX7ShcgBME=
  gem: dpl
  on:
    repo: travis-ci/dpl
    ruby: 2.2.6

notifications:
  webhooks: "http://requestb.in/1guaq7t1"
