language: shell

script:
  - true

before_deploy:
  - .travis/providers/github-pages/prepare

deploy:
  - provider: pages
    github_token:
      # personal access token with repo scope on travis-dpl-test
      secure: "fRVQWM14TO7/nHNyXB3fHZPKCqZxNPxN3wKmVsxVqTj99SSPsonr1AvQXziFtLEc44+pmlg0J5diFhhwzWU2W4/UxDaFyrdhkmZWRkRlJTjkgO0kDOJPJFza4stXAsavn4bLpz6YuCD0ZprPTBJu2wDA7e1IvXGRu0nb/PIaRko="
    repo: travis-ci/dpl_test
    local_dir: tmp/dpl_test
    keep_history: true
    verbose: true

after_deploy:
  - .travis/providers/github-pages/test || TRAVIS_TEST_RESULT=$?
